services:
  backend:
    build: ./backend
    container_name: jamescjordan_backend
    networks:
      - jamescjordan_net
    env_file: ./backend/.env
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health"]
      interval: 20s
      timeout: 3s
      retries: 5

  frontend:
    build: ./frontend
    container_name: jamescjordan_frontend
    networks:
      - jamescjordan_net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 20s
      timeout: 3s
      retries: 5

networks:
  jamescjordan_net:
    external: true
